set(CMAKE_C_VERBOSE_FLAG "-v")

string(APPEND CMAKE_C_FLAGS_MINSIZEREL_INIT " -DNDEBUG")
string(APPEND CMAKE_C_FLAGS_RELEASE_INIT " -DNDEBUG")

set(CMAKE_C90_STANDARD_COMPILE_OPTION  -h noc99,conform)
set(CMAKE_C90_EXTENSION_COMPILE_OPTION -h noc99,gnu)
set(CMAKE_C99_STANDARD_COMPILE_OPTION  -h c99,conform)
set(CMAKE_C99_EXTENSION_COMPILE_OPTION -h c99,gnu)
if(NOT CMAKE_C_COMPILER_VERSION VERSION_LESS 8.5)
  set(CMAKE_C11_STANDARD_COMPILE_OPTION  -h std=c11,conform)
  set(CMAKE_C11_EXTENSION_COMPILE_OPTION -h std=c11,gnu)
endif()

if(NOT CMAKE_C_COMPILER_VERSION VERSION_LESS 8.1)
  if (NOT CMAKE_C_COMPILER_FORCED)
    if (NOT CMAKE_C_STANDARD_COMPUTED_DEFAULT)
      message(FATAL_ERROR "CMAKE_C_STANDARD_COMPUTED_DEFAULT should be set for ${CMAKE_C_COMPILER_ID} (${CMAKE_C_COMPILER}) version ${CMAKE_C_COMPILER_VERSION}")
    endif()
    set(CMAKE_C_STANDARD_DEFAULT ${CMAKE_C_STANDARD_COMPUTED_DEFAULT})
  elseif(NOT DEFINED CMAKE_C_STANDARD_DEFAULT)
    # Compiler id was forced so just guess the default standard level.
    set(CMAKE_C_STANDARD_DEFAULT 99)
  endif()
endif()

macro(cmake_record_c_compile_features)
  foreach(STD IN ITEMS 90 99 11)
    record_compiler_features(C "${CMAKE_C${STD}_STANDARD_COMPILE_OPTION}"
      CMAKE_C${STD}_COMPILE_FEATURES)
  endforeach()
endmacro()

